### PR TITLE
refactor:  InviteUserTest

### LINKED ISSUE #27: Refactor InviteUserTest

### PR DESCRIPTION
**Pull request by bohrnsen**
resolves #27

### CODE REVIEW

**Comment by bohrnsen** [comment]
I made some smaller improvements in the documentation comments.

**Comment by bohrnsen** [comment]
This Pull Request may interfere with #21. The question is if we should use a base class or merging them together into one big test case. See InviteUserTest and InvitationsTestCase.

**Comment by AdderAdder** [comment]
I'll look into it @bohrnsen

**Comment by AdderAdder** [comment]
Indeed we'll get a merge conflict between this pull request and #21 but I don't think it will be that big of a problem (if we merge this pull request first then I can deal with the merge conflict, I have a rough idea of how to solve it). 

As for whether the test classes should be merged or not I would say no because the classes still represent rather different test cases. So it think the base class idea is better. But of course that's just my opinion and as the author of the refactoring @bohrnsen I think it's best if you decided. Just let me know when I should merge this pull request!

**Comment by bohrnsen** [comment]
I agree that the Base class may be the better option after all, giving the opportunity to divide this big class into separate ones in the future

**Pull request merged**
